# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8S94aAuL7_d2mNss_CVttShgzqh-3KM
"""

import os
import json
import ast
import time
import argparse
import pandas as pd
from typing import List, Optional
from pydantic import BaseModel, Field
from groq import Groq
from sentence_transformers import SentenceTransformer, util

# ==========================================
# PYDANTIC SCHEMAS
# ==========================================
class HardFilters(BaseModel):
    locations: List[str] = Field(default=[], description="OBLIGATORIU: Returnează DOAR coduri de țară ISO de 2 litere (ex: 'us', 'ro', 'ch', 'fr'). Dacă userul cere o regiune, returnează lista cu codurile țărilor majore din acea regiune.")
    min_employees: Optional[int] = Field(default=None)
    max_employees: Optional[int] = Field(default=None)
    min_revenue: Optional[int] = Field(default=None)
    max_revenue: Optional[int] = Field(default=None)
    min_founded_year: Optional[int] = Field(default=None)
    is_public: Optional[bool] = Field(default=None)

class SearchIntent(BaseModel):
    hard_filters: HardFilters
    semantic_query: str = Field(description="Frază scurtă (2-6 cuvinte) pentru Vector Search.")

class CompanyEvaluation(BaseModel):
    operational_name: str
    reasoning: str = Field(description="Analizează pas cu pas compatibilitatea firmei cu intenția și filtrele.")
    relevance_score: int = Field(description="Scor de la 0 la 100 bazat pe grila de evaluare.")

class EvaluationList(BaseModel):
    evaluations: List[CompanyEvaluation]

# ==========================================
# CORE MODULES
# ==========================================
class IntentParser:
    def __init__(self, client: Groq, model_name: str):
        self.client = client
        self.model_name = model_name

    def parse(self, user_query: str) -> dict:
        schema_json = SearchIntent.model_json_schema()
        try:
            res = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": f"Ești un sistem strict de extragere a intenției de căutare. Răspunde STRICT cu JSON valid: {json.dumps(schema_json)}"},
                    {"role": "user", "content": f"Query: '{user_query}'"}
                ],
                model=self.model_name, temperature=0.0, response_format={"type": "json_object"}
            )
            return SearchIntent(**json.loads(res.choices[0].message.content)).model_dump()
        except Exception as e:
            print(f"Intent Parser Error: {e}")
            return None

class FastRetriever:
    def __init__(self, df: pd.DataFrame):
        self.df = df
        self.embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

    def retrieve(self, intent: dict, top_k: int = 15) -> list:
        filters = intent.get('hard_filters', {})
        sem_query = intent.get('semantic_query', "")

        mask = pd.Series(True, index=self.df.index)

        if filters.get('locations'):
            valid_countries = [loc.lower() for loc in filters['locations']]
            mask = mask & (self.df['country_code'].isin(valid_countries) | self.df['country_code'].isna())

        if filters.get('min_employees'):
            mask = mask & ((self.df['employee_count'] >= filters['min_employees']) | self.df['employee_count'].isna())
        if filters.get('max_employees'):
            mask = mask & ((self.df['employee_count'] <= filters['max_employees']) | self.df['employee_count'].isna())
        if filters.get('min_revenue'):
            mask = mask & ((self.df['revenue'] >= filters['min_revenue']) | self.df['revenue'].isna())
        if filters.get('min_founded_year'):
            mask = mask & ((self.df['year_founded'] >= filters['min_founded_year']) | self.df['year_founded'].isna())
        if filters.get('is_public') is not None:
            mask = mask & (self.df['is_public'] == filters['is_public'])

        filtered_df = self.df[mask].copy()
        if filtered_df.empty:
            return []

        if sem_query:
            q_emb = self.embedding_model.encode(sem_query, convert_to_tensor=True)
            c_emb = self.embedding_model.encode(filtered_df['description'].tolist(), convert_to_tensor=True)
            filtered_df['semantic_score'] = util.cos_sim(q_emb, c_emb)[0].cpu().numpy()
            filtered_df = filtered_df.sort_values(by='semantic_score', ascending=False)

        top_df = filtered_df.head(top_k)
        return top_df[['operational_name', 'year_founded', 'employee_count', 'description']].to_dict('records')

class DeepJudge:
    def __init__(self, client: Groq, model_name: str):
        self.client = client
        self.model_name = model_name

    def rank(self, user_query: str, candidates: list) -> list:
        if not candidates:
            return []

        schema_json = EvaluationList.model_json_schema()
        companies_text = "\n".join([f"- Nume: {c['operational_name']}, An: {c['year_founded']}, Angajați: {c['employee_count']}\n  Descriere: {c['description'][:350]}" for c in candidates])

        system_prompt = f"""
        Ești un analist de business. Evaluează candidații față de cerința utilizatorului.
        Răspunde STRICT cu JSON valid: {json.dumps(schema_json)}

        GRILA DE EVALUARE (Tiers):
        [90-100] Potrivire Perfectă: Toate filtrele stricte și intenția semantică respectate clar.
        [70-89] Potrivire Bună: Intenția semantică este atinsă. Lipsesc date numerice (nan), dar descrierea sugerează o potrivire.
        [40-69] Potrivire Parțială: Industria are legătură, dar ratează flagrant un filtru major.
        [0-39] Irelevant: Nu are legătură cu intenția principală.

        REGULI STRICTE DE REDACTARE:
        1. NU folosi note rotunde (multipli de 10). Folosește note specifice (ex: 83, 94, 76, 42) pentru departajare fină.
        2. Fii direct în 'reasoning'. Scrie sub formă de notițe scurte. EVITĂ limbajul repetitiv.
        3. Scrie 'reasoning' MAI ÎNTÂI, apoi dă nota!
        """

        try:
            res = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Cerința: '{user_query}'\n\nCompanii:\n{companies_text}"}
                ],
                model=self.model_name, temperature=0.0, response_format={"type": "json_object"}
            )
            evals = EvaluationList(**json.loads(res.choices[0].message.content)).evaluations
            evals.sort(key=lambda x: x.relevance_score, reverse=True)
            return [e.model_dump() for e in evals]
        except Exception as e:
            print(f"Reranker Error: {e}")
            return []

class VeridionSearchEngine:
    def __init__(self, data_path: str, api_key: str):
        self.client = Groq(api_key=api_key)
        self.llm_model = "llama-3.3-70b-versatile"

        try:
            with open(data_path, 'r', encoding='utf-8') as f:
                df = pd.read_json(f, lines=True)
        except FileNotFoundError:
            raise FileNotFoundError(f"Fisierul de date nu a fost gasit la calea: {data_path}")

        self.parser = IntentParser(self.client, self.llm_model)
        self.retriever = FastRetriever(df)

        self.retriever.df['country_code'] = self.retriever.df['address'].apply(
            lambda x: ast.literal_eval(x).get('country_code', '').lower() if isinstance(x, str) else (x.get('country_code', '').lower() if isinstance(x, dict) else None)
        )
        self.retriever.df['year_founded'] = pd.to_numeric(self.retriever.df['year_founded'], errors='coerce')
        self.retriever.df['employee_count'] = pd.to_numeric(self.retriever.df['employee_count'], errors='coerce')
        self.retriever.df['revenue'] = pd.to_numeric(self.retriever.df['revenue'], errors='coerce')
        self.retriever.df['description'] = self.retriever.df['description'].fillna("")

        self.judge = DeepJudge(self.client, self.llm_model)

    def search(self, user_query: str) -> list:
        intent = self.parser.parse(user_query)
        if not intent:
            return []

        candidates = self.retriever.retrieve(intent, top_k=10)
        return self.judge.rank(user_query, candidates)

# ==========================================
# EXECUTION (CLI)
# ==========================================
def main():
    parser = argparse.ArgumentParser(description="Veridion Search Intent Challenge - Hybrid RAG")
    parser.add_argument("--data", type=str, default="companies.jsonl", help="Calea catre fisierul de date")
    parser.add_argument("--query", type=str, help="Ruleaza o interogare specifica. Daca este omis, ruleaza testele oficiale.")
    args = parser.parse_args()

    # Note for evaluators:
    # For testing convenience, a temporary Groq API key is included below.
    # I am aware that hardcoding keys is a bad security practice.
    # This key will be revoked once the evaluation process is complete.
    api_key = "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"

    print("Initializare sistem (incarcare date si model vectorial local)...")
    try:
        engine = VeridionSearchEngine(data_path=args.data, api_key=api_key)
    except Exception as e:
        print(f"Error: {e}")
        return

    print("Sistem pregatit.\n")

    if args.query:
        print(f"Cautare: '{args.query}'")
        start_t = time.time()
        results = engine.search(args.query)
        end_t = time.time()

        print(f"Timp executie: {end_t - start_t:.2f} secunde")
        if not results:
            print("Niciun rezultat gasit.")
        else:
            for j, r in enumerate(results):
                print(f"  {j+1}. [{r['relevance_score']}/100] {r['operational_name']}")
                print(f"      Logica: {r['reasoning']}\n")
    else:
        official_queries = [
            "Logistic companies in Romania",
            "Public software companies with more than 1,000 employees.",
            "Food and beverage manufacturers in France",
            "Companies that could supply packaging materials for a direct-to-consumer cosmetics brand",
            "Construction companies in the United States with revenue over $50 million",
            "Pharmaceutical companies in Switzerland",
            "B2B SaaS companies providing HR solutions in Europe",
            "Clean energy startups founded after 2018 with fewer than 200 employees",
            "Fast-growing fintech companies competing with traditional banks in Europe.",
            "E-commerce companies using Shopify or similar platforms",
            "Renewable energy equipment manufacturers in Scandinavia",
            "Companies that manufacture or supply critical components for electric vehicle battery production"
        ]

        print("Incepem rularea celor 12 interogari oficiale...")
        for i, query in enumerate(official_queries):
            print("-" * 80)
            print(f"Test [{i+1}/12]: '{query}'")
            start_t = time.time()
            results = engine.search(query)
            end_t = time.time()

            print(f"Timp executie: {end_t - start_t:.2f} secunde")
            if not results:
                print("Niciun rezultat gasit.")
            else:
                for j, r in enumerate(results):
                    print(f"  {j+1}. [{r['relevance_score']}/100] {r['operational_name']}")
                    print(f"      Logica: {r['reasoning']}\n")

            if i < len(official_queries) - 1:
                print("Pauza 2.5s pentru limitarea de rate-limit a API-ului...")
                time.sleep(2.5)

if __name__ == "__main__":
    main()